name: Build
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - uses: rinx/setup-graalvm-ce@v0.0.5
        with:
          graalvm-version: "22.1.0"
          java-version: "java11"
          native-image: "true"
      - run: sbt assembly
      - run: sbt nativeImage
      - run: mv target/scala-2.13/cliche-assembly*.jar target/scala-2.13/cliche.jar
      - uses: actions/upload-artifact@v3
        with:
          name: cliche.bin
          path: target/native-image/cliche
      - uses: actions/upload-artifact@v3
        with:
          name: cliche.jar
          path: target/scala-2.13/cliche.jar
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: ${{ github.ref }}
          title: ${{ github.ref_name }}
          files: |
            ./target/native-image/cliche
            ./target/scala-2.13/cliche.jar
